### ISSUE TITLE
some error i get.

### ISSUE THREAD

**Issue by Oyplap** [Kamshak/ps2-permaweaps#1]
[ps2-permaweaps-master] addons/ps2-permaweaps-master/lua/ps2/modules/weapons/sv_firstroundfix.lua:3: attempt to index field 'fullyLoadedPromise' (a nil value)
  1. v - addons/ps2-permaweaps-master/lua/ps2/modules/weapons/sv_firstroundfix.lua:3
   2. Call - lua/includes/modules/hook.lua:84
    3. v - gamemodes/deathrun/gamemode/init.lua:211
     4. unknown - lua/includes/modules/hook.lua:84
      5. Spawn - [C]:-1
       6. OnEnter - gamemodes/deathrun/gamemode/sh_definerounds.lua:263
        7. RoundSwitch - gamemodes/deathrun/gamemode/roundsystem/sv_round.lua:16
         8. unknown - gamemodes/deathrun/gamemode/sh_definerounds.lua:373

dunno what it is

**Comment by Oyplap** [comment]
This issue happens because an other addon is interfering with it (again discordintegration).

**Comment by Oyplap** [comment]
Apparently it is not on his end. nor xAdmin2's end. Could you help me out on this one?

**Comment by ValentinFunk** [comment]
Something that can happen if you just have too many addons in general gmod will refuse to load some lua files, that could be it perhaps

**Comment by Oyplap** [comment]
i searched it on google and i only have 10 addons currently.

https://www.google.com/search?sxsrf=ALeKk033LSU-Oj_9AVBMspzhALtDFMoTtA%3A1594388673283&ei=wXAIX8r6EMiAkwWgxIz4AQ&q=how+many+addons+can+you+have+on+a+gmod+server&oq=how+many+addons+can+you+have+on+a+gmod+server&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToGCCMQJxATOgYIABAWEB46BQgAEMsBOgUIIRCgAToECCEQFVCcyQJYk9oCYNTaAmgCcAB4AIABXIgBzQuSAQIyMpgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwiK34TU6MLqAhVIwKQKHSAiAx8Q4dUDCAw&uact=5

**Comment by Oyplap** [comment]
I think i'll close this issue down because i am 90% sure it is discord integration's fault. Already got a ticket send to him. Thank you for your help btw!
